CREATE TABLE "TB_ITEM_NF" (
	"ID" INTEGER NOT NULL,
	"QTD" INTEGER NOT NULL,
	"VALOR" REAL NOT NULL,
	"NUM_NF" INTEGER,
	"COD_PROD" INTEGER,
	FOREIGN KEY("NUM_NF") REFERENCES "TB_NOTAFISCAL" ("NUM_NF"),
	FOREIGN KEY("COD_PROD") REFERENCES "TB_PRODUTO" ("COD_PROD"),
	PRIMARY KEY("ID", "NUM_NF", "COD_PROD")
);
