CREATE TABLE "TB_NOTAFISCAL" (
	"ID" INTEGER NOT NULL,
	"ID_CLI" INTEGER,
	"ID_VEND" INTEGER,
	"COD_CLI" INTEGER,
	"COD_VEND" INTEGER,
	"NUM_NF" INTEGER NOT NULL UNIQUE,
	"SERIE_NF" INTEGER NOT NULL UNIQUE,
	FOREIGN KEY("ID_CLI") REFERENCES "TB_CLIENTES" ("ID"),
	FOREIGN KEY("ID_VEND") REFERENCES "TB_VENDEDORES" ("ID"),
	FOREIGN KEY("COD_CLI") REFERENCES "TB_CLIENTES" ("COD_CLI"),
	PRIMARY KEY("ID" AUTOINCREMENT)
);
